const data = [
    {
        title: 'CouCitytry 1',
        selected: false,
        nodex: [
            { title: 'City 1.1', selected: false },
            { title: 'City 1.2', selected: false },
            { title: 'City 1.3', selected: false },
            { title: 'City 1.4', selected: false },
            { title: 'City 1.5', selected: false },
            { title: 'City 1.6', selected: false },
            { title: 'City 1.7', selected: false },
            { title: 'City 1.8', selected: false },
            { title: 'City 1.9', selected: false },
            { title: 'City 1.10', selected: false },
        ],
    },
    {
        title: 'Country 2',
        selected: false,
        nodex: [
            { title: 'City 2.1', selected: false },
            { title: 'City 2.2', selected: false },
            { title: 'City 2.3', selected: false },
            { title: 'City 2.4', selected: false },
            { title: 'City 2.5', selected: false },
            { title: 'City 2.6', selected: false },
            { title: 'City 2.7', selected: false },
            { title: 'City 2.8', selected: false },
            { title: 'City 2.9', selected: false },
            { title: 'City 2.10', selected: false },
        ],
    },
    {
        title: 'Country 3',
        selected: false,
        nodex: [
            { title: 'City 3.1', selected: false },
            { title: 'City 3.2', selected: false },
            { title: 'City 3.3', selected: false },
            { title: 'City 3.4', selected: false },
            { title: 'City 3.5', selected: false },
            { title: 'City 3.6', selected: false },
            { title: 'City 3.7', selected: false },
            { title: 'City 3.8', selected: false },
            { title: 'City 3.9', selected: false },
            { title: 'City 3.10', selected: false },
        ],
    },
    {
        title: 'Country 4',
        selected: false,
        nodex: [
            { title: 'City 4.1', selected: false },
            { title: 'City 4.2', selected: false },
            { title: 'City 4.3', selected: false },
            { title: 'City 4.4', selected: false },
            { title: 'City 4.5', selected: false },
            { title: 'City 4.6', selected: false },
            { title: 'City 4.7', selected: false },
            { title: 'City 4.8', selected: false },
            { title: 'City 4.9', selected: false },
            { title: 'City 4.10', selected: false },
        ],
    },
    {
        title: 'Country 5',
        selected: false,
        nodex: [
            { title: 'City 5.1', selected: false },
            { title: 'City 5.2', selected: false },
            { title: 'City 5.3', selected: false },
            { title: 'City 5.4', selected: false },
            { title: 'City 5.5', selected: false },
            { title: 'City 5.6', selected: false },
            { title: 'City 5.7', selected: false },
            { title: 'City 5.8', selected: false },
            { title: 'City 5.9', selected: false },
            { title: 'City 5.10', selected: false },
        ],
    },
    {
        title: 'Country 6',
        selected: false,
        nodex: [
            { title: 'City 6.1', selected: false },
            { title: 'City 6.2', selected: false },
            { title: 'City 6.3', selected: false },
            { title: 'City 6.4', selected: false },
            { title: 'City 6.5', selected: false },
            { title: 'City 6.6', selected: false },
            { title: 'City 6.7', selected: false },
            { title: 'City 6.8', selected: false },
            { title: 'City 6.9', selected: false },
            { title: 'City 6.10', selected: false },
        ],
    },
    {
        title: 'Country 7',
        selected: false,
        nodex: [
            { title: 'City 7.1', selected: false },
            { title: 'City 7.2', selected: false },
            { title: 'City 7.3', selected: false },
            { title: 'City 7.4', selected: false },
            { title: 'City 7.5', selected: false },
            { title: 'City 7.6', selected: false },
            { title: 'City 7.7', selected: false },
            { title: 'City 7.8', selected: false },
            { title: 'City 7.9', selected: false },
            { title: 'City 7.10', selected: false },
        ],
    },
    {
        title: 'Country 8',
        selected: false,
        nodex: [
            { title: 'City 8.1', selected: false },
            { title: 'City 8.2', selected: false },
            { title: 'City 8.3', selected: false },
            { title: 'City 8.4', selected: false },
            { title: 'City 8.5', selected: false },
            { title: 'City 8.6', selected: false },
            { title: 'City 8.7', selected: false },
            { title: 'City 8.8', selected: false },
            { title: 'City 8.9', selected: false },
            { title: 'City 8.10', selected: false },
        ],
    },
    {
        title: 'Country 9',
        selected: false,
        nodex: [
            { title: 'City 9.1', selected: false },
            { title: 'City 9.2', selected: false },
            { title: 'City 9.3', selected: false },
            { title: 'City 9.4', selected: false },
            { title: 'City 9.5', selected: false },
            { title: 'City 9.6', selected: false },
            { title: 'City 9.7', selected: false },
            { title: 'City 9.8', selected: false },
            { title: 'City 9.9', selected: false },
            { title: 'City 9.10', selected: false },
        ],
    },
    {
        title: 'Country 10',
        selected: false,
        nodex: [
            { title: 'City 10.1', selected: false },
            { title: 'City 10.2', selected: false },
            { title: 'City 10.3', selected: false },
            { title: 'City 10.4', selected: false },
            { title: 'City 10.5', selected: false },
            { title: 'City 10.6', selected: false },
            { title: 'City 10.7', selected: false },
            { title: 'City 10.8', selected: false },
            { title: 'City 10.9', selected: false },
            { title: 'City 10.10', selected: false },
        ],
    },
];

